"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api-client";
import { ArtifactItem } from "@/lib/types";
import {
  FileCheck2,
  Download,
  ShieldCheck,
  FileText,
  CheckCircle2,
  Copy,
  Check,
  Clock,
  Sparkles,
  FileCode,
  FileType,
  Trash2,
  RefreshCw,
  Layers,
  ArrowRight,
} from "lucide-react";
import Link from "next/link";

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<ArtifactItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [copiedHash, setCopiedHash] = useState<string | null>(null);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const loadArtifacts = async (silent = false) => {
    try {
      if (!silent) setLoading(true);
      const data = await api.getArtifacts();
      setArtifacts(data);
    } catch (e) {
      console.error("Failed to load deliverables:", e);
    } finally {
      if (!silent) setLoading(false);
    }
  };

  useEffect(() => {
    loadArtifacts();
    const interval = setInterval(() => {
      loadArtifacts(true);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  const handleCopyHash = (hash: string) => {
    navigator.clipboard.writeText(hash);
    setCopiedHash(hash);
    setTimeout(() => setCopiedHash(null), 2000);
  };

  const handleDelete = async (artifactId: string, filename: string) => {
    if (!confirm(`Permanently delete deliverable '${filename}'?`)) return;

    try {
      setDeletingId(artifactId);
      await api.deleteArtifact(artifactId);
      setArtifacts((prev) => prev.filter((a) => a.artifact_id !== artifactId));
    } catch (e) {
      console.error("Failed to delete artifact:", e);
      alert("Failed to delete deliverable.");
    } finally {
      setDeletingId(null);
    }
  };

  const getDeliverableIcon = (filename: string) => {
    const ext = filename.split(".").pop()?.toLowerCase();
    if (["docx", "doc"].includes(ext || "")) {
      return <FileType className="w-5 h-5 text-iron-accentPrimary" />;
    }
    if (["pdf"].includes(ext || "")) {
      return <FileText className="w-5 h-5 text-rose-400" />;
    }
    if (["py"].includes(ext || "")) {
      return <FileCode className="w-5 h-5 text-iron-accentSecondary" />;
    }
    return <FileCheck2 className="w-5 h-5 text-iron-success" />;
  };

  return (
    <div className="space-y-6 animate-fade-in pb-16 font-sans">
      {/* Header Banner - Unwanted Create DOCX and Refresh buttons removed */}
      <div className="enterprise-card p-6 rounded-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <FileCheck2 className="w-5 h-5 text-iron-success" />
            <h1 className="text-xl font-bold text-iron-textPrimary tracking-tight">
              Generated Business Deliverables
            </h1>
            <span className="px-2 py-0.5 rounded bg-iron-success/15 border border-iron-success/40 text-iron-success text-[10px] font-mono font-bold">
              VERIFIED ATTESTATIONS
            </span>
          </div>
          <p className="text-xs text-iron-textSecondary max-w-3xl">
            Real Microsoft Word (.docx), Python (.py), and Excel (.xlsx) deliverables generated by local AI models with SHA-256 cryptographic provenance and sandbox verification.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Link
            href="/workbench"
            className="px-3.5 py-1.5 rounded-lg bg-iron-accentPrimary/15 hover:bg-iron-accentPrimary/25 text-iron-accentPrimary border border-iron-accentPrimary/30 text-xs font-mono font-semibold transition flex items-center gap-1.5"
          >
            <span>Run New Task</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>

      {/* Deliverables Roster */}
      <div className="space-y-3.5">
        {artifacts.length === 0 ? (
          <div className="enterprise-card p-16 text-center rounded-xl space-y-3">
            <FileCheck2 className="w-8 h-8 text-iron-textSecondary/40 mx-auto" />
            <div className="text-sm font-bold text-iron-textPrimary">No deliverables generated yet</div>
            <p className="text-xs text-iron-textSecondary max-w-sm mx-auto">
              Run an approval note or coding task in the Workbench to generate deliverables with cryptographic proofs.
            </p>
            <Link
              href="/workbench"
              className="inline-block mt-2 text-xs text-iron-accentPrimary font-semibold hover:underline font-mono"
            >
              Open Workbench →
            </Link>
          </div>
        ) : (
          artifacts.map((art) => {
            const downloadHref = `http://127.0.0.1:8000/api/v1/artifacts/${art.artifact_id}/download`;
            const sizeKb = art.size_bytes ? (art.size_bytes / 1024).toFixed(1) : "0";
            const isDeleting = deletingId === art.artifact_id;

            return (
              <div
                key={art.artifact_id}
                className="enterprise-card p-5 rounded-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4 transition hover:border-iron-border"
              >
                <div className="flex items-center space-x-4">
                  <div className="w-11 h-11 rounded-lg bg-iron-panelSecondary border border-iron-border flex items-center justify-center shrink-0">
                    {getDeliverableIcon(art.filename)}
                  </div>
                  <div className="space-y-1">
                    <div className="flex items-center gap-2.5">
                      <span className="font-bold text-sm text-iron-textPrimary">{art.filename}</span>
                      <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded bg-iron-success/15 text-iron-success border border-iron-success/30 uppercase">
                        {art.type || "Deliverable"}
                      </span>
                    </div>
                    <div className="flex flex-wrap items-center gap-3 text-xs text-iron-textSecondary font-mono">
                      <span>ID: {art.artifact_id}</span>
                      <span>•</span>
                      <span>{sizeKb} KB</span>
                      {art.created_at && (
                        <>
                          <span>•</span>
                          <span>{new Date(art.created_at).toLocaleTimeString()}</span>
                        </>
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2.5 w-full md:w-auto justify-end pt-2 md:pt-0 border-t md:border-t-0 border-iron-border/60">
                  {/* Cryptographic SHA-256 copy button */}
                  {art.sha256_hash && (
                    <button
                      onClick={() => handleCopyHash(art.sha256_hash)}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-iron-panelSecondary border border-iron-border text-iron-textSecondary hover:text-iron-textPrimary text-xs font-mono transition cursor-pointer"
                      title="Copy SHA-256 Hash"
                    >
                      {copiedHash === art.sha256_hash ? (
                        <Check className="w-3.5 h-3.5 text-iron-success" />
                      ) : (
                        <Copy className="w-3.5 h-3.5 text-iron-textSecondary" />
                      )}
                      <span>{art.sha256_hash.substring(0, 10)}...</span>
                    </button>
                  )}

                  {/* Download deliverable button */}
                  <a
                    href={downloadHref}
                    download
                    className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-iron-accentPrimary/15 hover:bg-iron-accentPrimary/25 text-iron-accentPrimary border border-iron-accentPrimary/30 font-semibold text-xs font-mono transition"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download</span>
                  </a>

                  {/* Delete deliverable button */}
                  <button
                    onClick={() => handleDelete(art.artifact_id, art.filename)}
                    disabled={isDeleting}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-iron-panelSecondary hover:bg-iron-error/15 text-iron-textSecondary hover:text-iron-error border border-iron-border hover:border-iron-error/40 text-xs font-mono transition cursor-pointer disabled:opacity-50"
                    title="Delete deliverable"
                  >
                    {isDeleting ? (
                      <RefreshCw className="w-3.5 h-3.5 animate-spin text-iron-error" />
                    ) : (
                      <Trash2 className="w-3.5 h-3.5" />
                    )}
                    <span>Delete</span>
                  </button>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
